"""本地沙盒适配器数据端口."""

from __future__ import annotations

from typing import Any, Protocol

from neobot_contracts.models import ConversationRef


class SandboxDataPort(Protocol):
    """Local adapter sandbox state boundary.

    端口只描述沙盒状态能力；OneBot 响应包装和事件投递由 adapter 层负责。
    """

    @property
    def bot_user_id(self) -> int: ...

    @property
    def bot_name(self) -> str: ...

    def next_message_id(self) -> int: ...
    def add_event(
        self,
        event: dict[str, Any],
        *,
        direction: str,
        conversation_name: str = "",
    ) -> Any | None: ...
    def add_outgoing(
        self,
        conversation: ConversationRef,
        message: str | list[dict[str, Any]],
    ) -> Any: ...
    def get_msg(self, message_id: int) -> Any | None: ...
    def list_conversations(self) -> list[Any]: ...
    def list_messages(
        self,
        conversation: ConversationRef,
        *,
        limit: int = 50,
        before_message_id: int | None = None,
    ) -> list[Any]: ...
    def history(
        self,
        conversation: ConversationRef,
        *,
        count: int = 20,
        message_seq: int = 0,
        reverse_order: bool = False,
    ) -> list[dict[str, Any]]: ...
    def to_onebot_message_data(self, message: Any) -> dict[str, Any]: ...

    async def reset(self) -> None: ...
    async def export_state(self) -> dict[str, Any]: ...
    async def load_state(self, state: dict[str, Any]) -> None: ...
    async def flush(self) -> None: ...

    async def upsert_user(self, user: dict[str, Any]) -> dict[str, Any]: ...
    async def get_user(self, user_id: str) -> dict[str, Any] | None: ...

    async def upsert_friend(self, friend: dict[str, Any]) -> dict[str, Any]: ...
    async def delete_friend(self, user_id: str) -> bool: ...
    async def list_friends(self) -> list[dict[str, Any]]: ...
    async def set_friend_remark(self, user_id: str, remark: str | None) -> dict[str, Any] | None: ...

    async def upsert_group(self, group: dict[str, Any]) -> dict[str, Any]: ...
    async def get_group(self, group_id: str) -> dict[str, Any] | None: ...
    async def list_groups(self) -> list[dict[str, Any]]: ...

    async def upsert_group_member(self, group_id: str, member: dict[str, Any]) -> dict[str, Any]: ...
    async def remove_group_member(self, group_id: str, user_id: str) -> bool: ...
    async def get_group_member(self, group_id: str, user_id: str) -> dict[str, Any] | None: ...
    async def list_group_members(self, group_id: str) -> list[dict[str, Any]]: ...

    async def mark_message_deleted(self, message_id: int, operator_id: int | str | None = None) -> dict[str, Any] | None: ...
    async def put_media(self, media: dict[str, Any]) -> dict[str, Any]: ...
    async def get_media(self, file: str) -> dict[str, Any] | None: ...

    async def create_friend_request(self, request: dict[str, Any]) -> dict[str, Any]: ...
    async def resolve_friend_request(
        self,
        flag: str,
        *,
        approve: bool,
        remark: str | None = None,
    ) -> dict[str, Any] | None: ...
    async def create_group_request(self, request: dict[str, Any]) -> dict[str, Any]: ...
    async def resolve_group_request(
        self,
        flag: str,
        *,
        approve: bool,
        reason: str | None = None,
    ) -> dict[str, Any] | None: ...

    async def put_forward_message(self, nodes: list[dict[str, Any]]) -> dict[str, Any]: ...
    async def bind_forward_message(self, forward_id: str, message_id: int) -> None: ...
    async def get_forward_message(self, lookup_id: str) -> dict[str, Any] | None: ...

    async def put_reaction(self, reaction: dict[str, Any]) -> dict[str, Any]: ...
    async def remove_reaction(self, message_id: int, emoji_id: str, user_id: str) -> bool: ...
    async def list_reactions(self, message_id: int) -> list[dict[str, Any]]: ...
