"""配置模型 — 统一导出"""

from neobot_app.config.schemas.bot import (
    AgentProblemSolver,
    Bot,
    BotConfig,
    Chat,
    Dashboard,
    DeepSeekModelSettings,
    AgentModelRouting,
    HuoShanTTS,
    KeyWordRule,
    ModelAssignments,
    ModelDefinition,
    ModelPricing,
    ModelRegistration,
    ModelSettings,
    Models,
    Message,
    Plugins,
    TTS,
    TTSReferenceVoice,
    WebSearchConfig,
)
from neobot_app.config.schemas.env import ApiPlatformConfig, EnvConfig

__all__ = [
    "AgentProblemSolver",
    "Bot",
    "BotConfig",
    "Chat",
    "Dashboard",
    "ApiPlatformConfig",
    "AgentModelRouting",
    "DeepSeekModelSettings",
    "EnvConfig",
    "KeyWordRule",
    "Message",
    "ModelAssignments",
    "ModelDefinition",
    "ModelPricing",
    "ModelRegistration",
    "ModelSettings",
    "Models",
    "Plugins",
    "TTS",
    "TTSReferenceVoice",
    "WebSearchConfig",
    "HuoShanTTS",
]
